# Generated by Django 4.0.1 on 2022-01-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='ens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
