# Generated by Django 4.0.1 on 2022-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_scored'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musique',
        ),
        migrations.DeleteModel(
            name='Nourriture',
        ),
        migrations.AddField(
            model_name='quizz',
            name='image',
            field=models.ImageField(default='aaa', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizz',
            name='theme',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizz',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
