# Generated by Django 4.0.1 on 2022-01-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_delete_quizz2_alter_quizz_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='scored',
            name='theme',
            field=models.CharField(choices=[('animaux', 'animaux'), ('musique', 'musique'), ('autres', 'autres')], default='animaux', max_length=100),
            preserve_default=False,
        ),
    ]
